services:
  zabbix-server:
    image: zabbix/zabbix-server-pgsql:latest
    container_name: zabbix-server
    depends_on:
      - postgres-server
    ports:
      - "10051:10051"
      
    environment:
      DB_SERVER_HOST: postgres-server
      POSTGRES_DB: zabbix
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: zabbix
    networks:
      - zabbix-net
    restart: unless-stopped

  postgres-server:
    image: postgres:15-alpine
    container_name: postgres-server
    environment:
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: zabbix
      POSTGRES_DB: zabbix
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./pg_hba.conf:/var/lib/postgresql/data/pg_hba.conf
    networks:
      - zabbix-net
    restart: unless-stopped

  zabbix-web:
    image: zabbix/zabbix-web-nginx-pgsql:latest 
    container_name: zabbix-web
    depends_on:
      - zabbix-server
    environment:
      DB_SERVER_HOST: postgres-server
      ZBX_SERVER_HOST: zabbix-server
    networks:
      - zabbix-net
     

  nginx-proxy:
    image: nginx:latest
    container_name: nginx-proxy
    volumes:
      - /opt/nginx/certs:/etc/nginx/certs:ro
      - /opt/nginx/conf:/etc/nginx/conf.d:ro
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - zabbix-web
    networks:
      - zabbix-net

  zabbix-agent:
    image: zabbix/zabbix-agent:alpine-latest
    container_name: zabbix-agent
    environment:
      ZBX_SERVER_HOST: zabbix-server
      ZBX_ACTIVE_SERVER: zabbix-server
    depends_on:
      - zabbix-server
    networks:
      - zabbix-net
     
    ports:
      - "10050:10050"
    restart: unless-stopped

networks:
  zabbix-net:
    driver: bridge

volumes:
  pg_data:

