

services:
  zabbix-server:
    image: zabbix/zabbix-server-pgsql:latest
    depends_on:
      - postgres-server
    environment:
      DB_SERVER_HOST: postgres-server
    networks:
      - backend

  postgres-server:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: zabbix
      POSTGRES_DB: zabbix
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - backend

  zabbix-web-nginx-pgsql:
    image: zabbix/zabbix-web-nginx-pgsql:latest
    depends_on:
      - zabbix-server
    environment:
      DB_SERVER_HOST: postgres-server
    networks:
      - backend
      - frontend

  nginx-proxy:
    image: nginx:latest
    container_name: nginx-proxy
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certs:/etc/nginx/certs:ro
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - zabbix-web-nginx-pgsql
    networks:
      - frontend

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge

volumes:
  pg_data:
